###########################################################
#                                                         #
#    Fill out this file and rename it to 'config.yaml'    #
#                                                         #
###########################################################

# The access token the bot will use to login to the Discord API
token: Discord Bot Token Here
# The emote which will be used under the giveaway message to 
# participate to the giveaway
emote: ✋
# Enter here all ROLE ID's AS STRING (in "") who should be 
# authorized to use the giveaway creation and closing command
authorized: [ "groupId1", "groupId2" ]